version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: restaurant-backend
    ports:
      - "7000:7000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/restaurantdb
      - PORT=7000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: restaurant-frontend
    ports:
      - "2000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
